#! /usr/bin/python

import json
import subprocess
import sys
from collections import OrderedDict

def calculate_cksum(file_name):
    with open(file_name) as x: f = x.read()
    ovsschema = json.loads(f, object_pairs_hook=OrderedDict)
    if 'cksum' in ovsschema:
        ovsschema.pop('cksum')
    cksum = subprocess.Popen(["cksum"], stdout=subprocess.PIPE,
                                        stdin=subprocess.PIPE)
    output, error = cksum.communicate(
            input=json.dumps(ovsschema, indent=4, separators=(',', ': '))
        )
    print output.rstrip().lstrip()

if __name__ == '__main__':
    calculate_cksum(sys.argv[1])
